<a href="https://colab.research.google.com/github/Shakil97/ActionBar/blob/master/banglaSongsLyrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade gspread

  Found existing installation: gspread 3.0.1
    Uninstalling gspread-3.0.1:
      Successfully uninstalled gspread-3.0.1


In [ ]:
!pip install bert-for-tf2
!pip install sentencepiece

     |████████████████████████████████| 51kB 4.0MB/s 
  Created wheel for bert-for-tf2: filename=bert_for_tf2-0.14.9-cp36-none-any.whl size=30534 sha256=61099fd4574cc621d854b91bb8cf33793d6bfb5ffdf230a68c19b28925565856
  Stored in directory: /root/.cache/pip/wheels/a1/04/ee/347bd9f5b821b637c76411d280271a857aece00358896a230f
  Created wheel for py-params: filename=py_params-0.10.1-cp36-none-any.whl size=7849 sha256=5d16c9d536739640f934457cb7cf9fb20feeeb495b56f80f72153cd2338cec60
  Stored in directory: /root/.cache/pip/wheels/fd/13/cf/731530f5760266e69a40217ea27fa0d39a2d2a67230a73e2bc
  Created wheel for params-flow: filename=params_flow-0.8.2-cp36-none-any.whl size=19474 sha256=5203ede20e85dd26d4e4939a8be2bef4f0f81de0fa4bd3885137ace9d7c63b62
  Stored in directory: /root/.cache/pip/wheels/08/c8/7f/81c86b9ff2b86e2c477e3914175be03e679e596067dc630c06
Successfully built bert-for-tf2 py-params params-flow
     |████████████████████████████████| 1.2MB 5.8MB/s 


In [ ]:
i = []
while True:
  i.append(i)


In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"fahimulislamshakil","key":"44731c1cd6d0f6cb331f2383544162dc"}'}

In [ ]:
!pip install kaggle

In [ ]:
from google.colab import files
files.upload()

Saving shortlyrics - Sheet1.json to shortlyrics - Sheet1.json


{'shortlyrics - Sheet1.json': b'[\r\n {\r\n   "title": "\xe0\xa6\x85\xe0\xa6\xaa\xe0\xa6\xb0\xe0\xa6\xbe\xe0\xa6\x9c\xe0\xa6\xbf\xe0\xa6\xa4",\r\n   "category": "\xe0\xa6\xac\xe0\xa7\x8d\xe0\xa6\xaf\xe0\xa6\xbe\xe0\xa6\xa8\xe0\xa7\x8d\xe0\xa6\xa1",\r\n   "lyrics": "\xe0\xa6\x8f\xe0\xa6\xac\xe0\xa6\xbe\xe0\xa6\xb0 \xe0\xa6\xa4\xe0\xa7\x8b\xe0\xa6\xae\xe0\xa6\xbe\xe0\xa6\xb0 \xe0\xa6\x95\xe0\xa6\xa5\xe0\xa6\xbe\xe0\xa6\x97\xe0\xa7\x81\xe0\xa6\xb2\xe0\xa7\x8b\xe0\xa6\xb0\\n\xe0\xa6\x95\xe0\xa6\xbe\xe0\xa6\x9b\xe0\xa7\x87 \xe0\xa6\x86\xe0\xa6\xae\xe0\xa6\xbf \xe0\xa6\x85\xe0\xa6\xaa\xe0\xa6\xb0\xe0\xa6\xbe\xe0\xa6\x9c\xe0\xa6\xbf\xe0\xa6\xa4\\n\xe0\xa6\x9c\xe0\xa6\xae\xe0\xa7\x87 \xe0\xa6\xa5\xe0\xa6\xbe\xe0\xa6\x95\xe0\xa6\xbe \xe0\xa6\xaf\xe0\xa6\xa4 \xe0\xa6\x85\xe0\xa6\xa8\xe0\xa7\x81\xe0\xa6\xad\xe0\xa7\x82\xe0\xa6\xa4\xe0\xa6\xbf \xe0\xa6\x86\xe0\xa6\xae\xe0\xa6\xbe\xe0\xa6\xb0\\n\xe0\xa6\x9c\xe0\xa6\xb2 \xe0\xa6\xb0\xe0\xa6\x99\xe0\xa7\x87 \xe0\xa6\xb9\xe0\xa6\xbe\xe0\xa6\xb0\xe0\xa

In [1]:
import json
with open('BanglaSongs.json', encoding='utf-8') as f:
    datastore = json.load(f)

sentences = []
labels = []


for item in datastore:
    sentences.append(item['lyrics'])
    labels.append(item['Mood'])

In [3]:

set (labels)

{'',
 ' প্রেম',
 ' বেদনা',
 'আনন্দ',
 'দেশপ্রেম',
 'দেশপ্রেম ',
 'ধার্মিক',
 'প্রেম',
 'বেদনা'}

In [4]:
categories = list (set (labels))

In [5]:
categories

['',
 'ধার্মিক',
 'আনন্দ',
 'বেদনা',
 'দেশপ্রেম ',
 ' বেদনা',
 'দেশপ্রেম',
 ' প্রেম',
 'প্রেম']

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
  sentences, labels, test_size=0.2, random_state=42)

In [7]:
!pip install ktrain

In [8]:
!pip install git+https://github.com/amaiya/eli5@tfkeras_0_10_1

  Cloning https://github.com/amaiya/eli5 (to revision tfkeras_0_10_1) to /tmp/pip-req-build-90meuoev
  Running command git clone -q https://github.com/amaiya/eli5 /tmp/pip-req-build-90meuoev
  Running command git checkout -b tfkeras_0_10_1 --track origin/tfkeras_0_10_1
  Switched to a new branch 'tfkeras_0_10_1'
  Branch 'tfkeras_0_10_1' set up to track remote branch 'tfkeras_0_10_1' from 'origin'.
  Created wheel for eli5: filename=eli5-0.10.1-py2.py3-none-any.whl size=106832 sha256=619e2bc6a42a349db7da7a365c06a9c5e12d761ff06ef0ea90377068980dfde1
  Stored in directory: /tmp/pip-ephem-wheel-cache-dojpbl4k/wheels/51/59/0a/0f48442b8d209583a4453580938d7ba2270aca40edacee6d45
Successfully built eli5


In [ ]:
!pip install -U sklearn

Requirement already up-to-date: sklearn in /usr/local/lib/python3.6/dist-packages (0.0)


In [9]:
import ktrain
from ktrain import text

In [ ]:
!pip uninstall ktrain

Uninstalling ktrain-0.25.3:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/ktrain-0.25.3.dist-info/*
    /usr/local/lib/python3.6/dist-packages/ktrain/*
Proceed (y/n)? y
  Successfully uninstalled ktrain-0.25.3


In [10]:
MODEL_NAME = 'sagorsarker/bangla-bert-base'
t = text.Transformer(MODEL_NAME, maxlen=500)

In [11]:

trn = t.preprocess_train(X_train, y_train)
val = t.preprocess_test(X_test, y_test)

preprocessing train...
language: bn
train sequence lengths:
	mean : 107
	95percentile : 200
	99percentile : 256


Is Multi-Label? False
preprocessing test...
language: bn
test sequence lengths:
	mean : 117
	95percentile : 198
	99percentile : 211


In [13]:
model = t.get_classifier()

In [14]:
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)

In [ ]:
%matplotlib inline
learner.lr_find(show_plot=True, max_epochs=4)

simulating training for different learning rates... this may take a few moments...
Epoch 1/4


In [24]:
learner.fit_onecycle(8e-5, 6)



begin training using onecycle policy with max lr of 8e-05...
Epoch 1/6
41/41 [==============================] - 1000s 24s/step - loss: 0.5077 - accuracy: 0.9004 - val_loss: 1.5563 - val_accuracy: 0.4098
Epoch 2/6
41/41 [==============================] - 1018s 25s/step - loss: 0.3637 - accuracy: 0.8880 - val_loss: 1.8113 - val_accuracy: 0.4262
Epoch 3/6
41/41 [==============================] - 932s 23s/step - loss: 0.1214 - accuracy: 0.9834 - val_loss: 2.6771 - val_accuracy: 0.3279
Epoch 4/6
41/41 [==============================] - 900s 22s/step - loss: 0.1535 - accuracy: 0.9627 - val_loss: 2.5142 - val_accuracy: 0.4426
Epoch 5/6
41/41 [==============================] - 892s 22s/step - loss: 0.1525 - accuracy: 0.9668 - val_loss: 2.1719 - val_accuracy: 0.3770
Epoch 6/6
41/41 [==============================] - 871s 21s/step - loss: 0.0722 - accuracy: 0.9834 - val_loss: 2.0591 - val_accuracy: 0.4754


In [ ]:

learner.validate(class_names=t.get_classes())

In [17]:
learner.view_top_losses(n=1, preproc=t)

----------
id:51 | loss:3.54 | true: | pred:বেদনা)



In [18]:
predictor = ktrain.get_predictor(learner.model, preproc=t)

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [26]:
# কেট্রেইন দিয়ে সেভ করা
predictor.save('/content/drive/MyDrive/Colab Notebooks/saved_model/bangla_songs_lyrics_kt')
# ট্রান্সফরমার্স এপিআই দিয়ে সেভ করি
learner.model.save_pretrained('/content/drive/MyDrive/Colab Notebooks/saved_model/bangla_songs_lyrics_predictor')

In [27]:
!ls -alh '/content/drive/MyDrive/Colab Notebooks/saved_model/bangla_songs_lyrics_predictor_kt'

ls: cannot access '/content/drive/MyDrive/Colab Notebooks/saved_model/bangla_songs_lyrics_predictor_kt': No such file or directory


In [28]:
!ls -ahl '/content/drive/MyDrive/Colab Notebooks/saved_model/bangla_songs_lyrics_predictor'

total 628M
-rw------- 1 root root  902 Jan 22 22:55 config.json
-rw------- 1 root root 628M Jan 22 22:56 tf_model.h5


In [29]:
learner.model.summary()

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  164396544 
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  6921      
Total params: 164,403,465
Trainable params: 164,403,465
Non-trainable params: 0
_________________________________________________________________


In [19]:
predictor.predict('মোরে ডেকে লও সেই দেশে প্রিয় যে দেশে তুমি থাক। মোর কি কাজ জীবনে বঁধূ যদি তুমি কাছে নাহি ডাক।। এই পৃথিবীর হাসি গান বঁধূ সব হয়ে যায় ম্লান,')

'বেদনা'

In [20]:
predictor.predict('তোমার মনে ফুটবে যবে প্রথম মুকুল। প্রিয় হে প্রিয় আমারে দিও সে প্রেমের মুকুল।।')

'প্রেম'

In [22]:
predictor.predict('আজি  আকুল ফুলসাজে জাগ’  মৃদুকম্পিত লাজে, মম  হৃদয়শয়নমাঝে, শুন  মধুর মুরলী বাজে মম   অন্তরে থাকি থাকি– সখি, জাগ’ জাগ’ ॥')

'বেদনা'

In [23]:
predictor.predict('আলোকের এই ঝর্নাধারায় ধুইয়ে দাও। আপনাকে এই লুকিয়ে-রাখা ধুলার ঢাকা ধুইয়ে দাও॥ যে জন   আমার মাঝে জড়িয়ে আছে ঘুমের জালে')

'আনন্দ'

In [30]:
from transformers import *
import tensorflow as tf
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = TFAutoModel.from_pretrained('/content/drive/MyDrive/Colab Notebooks/saved_model/bangla_songs_lyrics_predictor')
input_ids = tf.constant(tokenizer.encode("আমরা বাংলায় কথা বলি"))[None, :]  
outputs = model(input_ids)
last_hidden_states = outputs[0] 
print(last_hidden_states.numpy().shape)

(1, 7, 768)


In [31]:
last_hidden_states

<tf.Tensor: shape=(1, 7, 768), dtype=float32, numpy=
array([[[ 1.791471  , -0.7490264 , -1.6816239 , ..., -0.5195073 ,
         -0.73764026, -1.0236716 ],
        [ 0.81594545, -0.8927433 , -2.1332033 , ...,  0.6667134 ,
          0.52838117,  0.9586132 ],
        [ 0.3132732 , -0.86122334,  0.19442031, ...,  0.64588726,
          1.7279029 ,  0.39998233],
        ...,
        [ 1.8507001 , -1.2910967 , -1.6973629 , ..., -1.0770029 ,
         -0.00792767,  0.7532913 ],
        [ 0.32781732,  0.02771547,  0.1652026 , ..., -0.3544465 ,
          1.4773356 ,  0.93419725],
        [ 2.059452  , -0.3562409 , -1.4578389 , ..., -0.3897972 ,
          0.040133  , -0.35489112]]], dtype=float32)>

In [32]:
outputs

(<tf.Tensor: shape=(1, 7, 768), dtype=float32, numpy=
 array([[[ 1.791471  , -0.7490264 , -1.6816239 , ..., -0.5195073 ,
          -0.73764026, -1.0236716 ],
         [ 0.81594545, -0.8927433 , -2.1332033 , ...,  0.6667134 ,
           0.52838117,  0.9586132 ],
         [ 0.3132732 , -0.86122334,  0.19442031, ...,  0.64588726,
           1.7279029 ,  0.39998233],
         ...,
         [ 1.8507001 , -1.2910967 , -1.6973629 , ..., -1.0770029 ,
          -0.00792767,  0.7532913 ],
         [ 0.32781732,  0.02771547,  0.1652026 , ..., -0.3544465 ,
           1.4773356 ,  0.93419725],
         [ 2.059452  , -0.3562409 , -1.4578389 , ..., -0.3897972 ,
           0.040133  , -0.35489112]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[ 5.77195227e-01,  2.67647982e-01, -2.76279390e-01,
          3.90082449e-01, -5.03878772e-01, -5.54211497e-01,
          4.87963527e-01,  5.46492152e-02, -7.57601857e-01,
         -1.11064985e-01,  8.34820196e-02,  8.39536250e-01